### ISSUE TITLE
How to set pxz compression level with tar?

### ISSUE THREAD

**Issue by gotnix** [jnovy/pxz#27]
I know `xz` can read command line options from the environment variable `XZ_OPT` when i use it with `tar`, like this:
`XZ_OPT='-9' tar -cvJf /tmp/foo.txz foo-*.txt`
but `pxz` seems like not read environment variable, so how can i to do that?

**Comment by DaGeRe** [comment]
Just had the same problem, this can be done by `tar -I 'pxz -9' -cf tmp/foo.txz foo-*.txt`.

**Comment by jnovy** [comment]
The problem here is pxz doesn't forward environment to XZ itself. I was not aware you can influence XZ's behavior by env vars so I this this makes sense to implement as it's trivial.

**Comment by DaGeRe** [comment]
Thanks for the hint, I've implemented it and created a merge request: https://github.com/jnovy/pxz/pull/33

**Comment by jnovy** [comment]
Merged, thanks!
