### ISSUE TITLE
LeakSanitizer warnings memory leaks

### ISSUE THREAD

**Issue by HongxuChen** [jnovy/pxz#32]
At https://github.com/jnovy/pxz/blob/master/pxz.c#L338, the allocated memory is not freed. The problem is that  when there are *many files* to be processed at once (e.g., `./pxz -k -T 8 -q -f c-input/*`, and since the maximum argument length is 131072 on my machine, c.f. [here](https://unix.stackexchange.com/a/120842/8776)), it may eat up memories -- the allocations are inside a loop traversing the input files. Since each time the leaked memory is 25169920 on my machine, 25169920*131072=3.2990718e+12bytes, which is roughly 3200Gigabytes.
When the command lasts for a long time, it may also slowdown the host machine.

Also, as seen in #31, there is no upper bound limit for the specified thread number, this may lead to quick segfault.

**Comment by jnovy** [comment]
This is now fixed and merged to master.
